[build-system]
requires = ["setuptools>=80.9.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "midisimx"
version = "26.8.28"
description = "Calculate, search, and analyze MIDI-to-MIDI similarity at scale"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
  { name = "Alex Lev", email = "alexlev61@proton.me" }
]
maintainers = [
  { name = "Alex Lev", email = "alexlev61@proton.me" }
]
dependencies = [
  "tqdm",
  "ipywidgets",
  "huggingface_hub",
  "torch",
  "einops",
  "einx",
  "torch-summary",
  "matplotlib",
  "networkx",
  "scipy",
  "scikit-learn",
  "numpy"
]

keywords = [
	"MIDI",
	"music",
	"music AI",
	"MIR",
	"similarity",
	"similarity search",
	"symbolic music",
	"MIDI similarity",
	"music similarity",
	"cosine somilarity",
	"MIDI search",
	"music search",
        "music information retrieval",
        "music analysis",
        "MIDI analysis"
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Education",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Multimedia :: Sound/Audio",
  "Topic :: Multimedia :: Sound/Audio :: MIDI",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Environment :: Console",
  "Natural Language :: English",
  "Typing :: Typed"
]

requires-python = ">=3.8"

[project.readme]
file = "midisimx/README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/asigalov61/midisimx"
Documentation = "https://github.com/asigalov61/midisimx"
Models = "https://huggingface.co/projectlosangeles/midisimx"
Embeddings = "https://huggingface.co/datasets/projectlosangeles/midisimx-embeddings"
Samples = "https://huggingface.co/datasets/projectlosangeles/midisimx-samples"
Issues = "https://github.com/asigalov61/midisimx/issues"
Discussions = "https://github.com/asigalov61/midisimx/discussions"
Dataset = "https://huggingface.co/datasets/projectlosangeles/Discover-MIDI-Dataset"
SoundCloud = "https://soundcloud.com/aleksandr-sigalov-61/"
